<CustButton@Button>
    font_size: 24

<BoxLayout>:
    orientation: "vertical"
    spacing: 10
    padding: 10

    CustButton:
        text: "A.P. Chemistry"
    CustButton:
        text: "A.P. Latin"
    CustButton:
        text: "Honors English"
    CustButton:
        text: "Religion III"
    CustButton:
        text: "Spanish II"
    CustButton:
        text: "Pre-Calc"
    CustButton:
        text: "Rotation"
